### ISSUE TITLE
Requirements Error when Installing Development Version of ParrotFish

### ISSUE THREAD

**Issue by psinha25** [ubc-cirrus-lab/parrotfish#161]
I get the following issue below when attempting to make changes to the code and installing packages to run ParrotFish.

The 'grpcio-status<2.0.dev0,>=1.33.2; extra == "grpc"' distribution was not found and is required by google-api-core

**Comment by arshiamoghimi** [comment]
@psinha25 Can you provide me with your Linux and Python versions? I tried to reproduce the problems on an Ubuntu 22.04 machine with Python 3.10.12 installed, but it did not get to the same error. These were all the commands that I ran on the machine from the moment it booted:

```bash
sudo apt update
sudo apt install python3.10-venv
git clone https://github.com/ubc-cirrus-lab/parrotfish.git
cd parrotfish
python3 -m venv src-env
source src-env/bin/activate
export PACKAGE_VERSION="0.0.0"
pip install -e .
parrotfish
```

**Comment by psinha25** [comment]
@arshiamoghimi Strange, when you are trying to reproduce the problem, are you starting from a clean OS with no previous Python packages installed? My machine has some global package installations that may be causing the issue. Although, with a virtual environment I would think this issue wouldn't arise. 

Linux kernel version: 5.4.0-139-generic
Linux distro: Ubuntu 20.04.6 LTS
Python version: 3.8.10

**Comment by arshiamoghimi** [comment]
Sorry for the delayed response. I could replicate the problem with Python 3.8. It seems like Google Cloud package dependencies are different between different versions of Python, and the `grpcio-status` package does not get automatically installed on Python 3.8. Python 3.9 and above don't have this problem. A fix will be merged soon. Thanks again for reporting this issue.
